apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{  .Values.mysql.name  }}
spec:
  selector:
    matchLabels:
      app:  {{  .Values.mysql.name  }}
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app:  {{  .Values.mysql.name  }}
    spec:
      containers:
      - image: {{  .Values.mysql.container  }}
        name: {{  .Values.mysql.name  }} 
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secrets
              key: ROOT_PASSWORD
        - name: MYSQL_DATABASE
          value: {{ .Values.mysql.database }}
        - name: MYSQL_ROOT_HOST
          value: '%'
        ports:
        - containerPort:  {{  .Values.mysql.port  }}
          name: mysql
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
        - name: mysql-config
          mountPath: /etc/mysql/conf.d/
      serviceAccountName: {{  .Values.serviceAccount.name  }}
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pv-claim
      - name: mysql-config
        configMap: 
          name: mysql-config
